// Generated by gencpp from file hover_g2/BGR.msg
// DO NOT EDIT!


#ifndef HOVER_G2_MESSAGE_BGR_H
#define HOVER_G2_MESSAGE_BGR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hover_g2
{
template <class ContainerAllocator>
struct BGR_
{
  typedef BGR_<ContainerAllocator> Type;

  BGR_()
    : B(0)
    , G(0)
    , R(0)  {
    }
  BGR_(const ContainerAllocator& _alloc)
    : B(0)
    , G(0)
    , R(0)  {
  (void)_alloc;
    }



   typedef uint8_t _B_type;
  _B_type B;

   typedef uint8_t _G_type;
  _G_type G;

   typedef uint8_t _R_type;
  _R_type R;





  typedef boost::shared_ptr< ::hover_g2::BGR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hover_g2::BGR_<ContainerAllocator> const> ConstPtr;

}; // struct BGR_

typedef ::hover_g2::BGR_<std::allocator<void> > BGR;

typedef boost::shared_ptr< ::hover_g2::BGR > BGRPtr;
typedef boost::shared_ptr< ::hover_g2::BGR const> BGRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hover_g2::BGR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hover_g2::BGR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hover_g2::BGR_<ContainerAllocator1> & lhs, const ::hover_g2::BGR_<ContainerAllocator2> & rhs)
{
  return lhs.B == rhs.B &&
    lhs.G == rhs.G &&
    lhs.R == rhs.R;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hover_g2::BGR_<ContainerAllocator1> & lhs, const ::hover_g2::BGR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hover_g2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hover_g2::BGR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hover_g2::BGR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hover_g2::BGR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hover_g2::BGR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hover_g2::BGR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hover_g2::BGR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hover_g2::BGR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23e697e8143916dacd58cd4b2e3a98e8";
  }

  static const char* value(const ::hover_g2::BGR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23e697e8143916daULL;
  static const uint64_t static_value2 = 0xcd58cd4b2e3a98e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hover_g2::BGR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hover_g2/BGR";
  }

  static const char* value(const ::hover_g2::BGR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hover_g2::BGR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 B\n"
"uint8 G\n"
"uint8 R\n"
;
  }

  static const char* value(const ::hover_g2::BGR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hover_g2::BGR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.B);
      stream.next(m.G);
      stream.next(m.R);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BGR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hover_g2::BGR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hover_g2::BGR_<ContainerAllocator>& v)
  {
    s << indent << "B: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.B);
    s << indent << "G: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.G);
    s << indent << "R: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.R);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOVER_G2_MESSAGE_BGR_H
