// Generated by gencpp from file hover_g2/Movimento.msg
// DO NOT EDIT!


#ifndef HOVER_G2_MESSAGE_MOVIMENTO_H
#define HOVER_G2_MESSAGE_MOVIMENTO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hover_g2
{
template <class ContainerAllocator>
struct Movimento_
{
  typedef Movimento_<ContainerAllocator> Type;

  Movimento_()
    : X(0)
    , Z(0)  {
    }
  Movimento_(const ContainerAllocator& _alloc)
    : X(0)
    , Z(0)  {
  (void)_alloc;
    }



   typedef int32_t _X_type;
  _X_type X;

   typedef int32_t _Z_type;
  _Z_type Z;





  typedef boost::shared_ptr< ::hover_g2::Movimento_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hover_g2::Movimento_<ContainerAllocator> const> ConstPtr;

}; // struct Movimento_

typedef ::hover_g2::Movimento_<std::allocator<void> > Movimento;

typedef boost::shared_ptr< ::hover_g2::Movimento > MovimentoPtr;
typedef boost::shared_ptr< ::hover_g2::Movimento const> MovimentoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hover_g2::Movimento_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hover_g2::Movimento_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hover_g2::Movimento_<ContainerAllocator1> & lhs, const ::hover_g2::Movimento_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Z == rhs.Z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hover_g2::Movimento_<ContainerAllocator1> & lhs, const ::hover_g2::Movimento_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hover_g2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hover_g2::Movimento_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hover_g2::Movimento_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hover_g2::Movimento_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hover_g2::Movimento_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hover_g2::Movimento_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hover_g2::Movimento_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hover_g2::Movimento_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55060bc0bff810087528e2fd8dc35363";
  }

  static const char* value(const ::hover_g2::Movimento_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55060bc0bff81008ULL;
  static const uint64_t static_value2 = 0x7528e2fd8dc35363ULL;
};

template<class ContainerAllocator>
struct DataType< ::hover_g2::Movimento_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hover_g2/Movimento";
  }

  static const char* value(const ::hover_g2::Movimento_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hover_g2::Movimento_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 X\n"
"int32 Z\n"
;
  }

  static const char* value(const ::hover_g2::Movimento_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hover_g2::Movimento_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Movimento_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hover_g2::Movimento_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hover_g2::Movimento_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<int32_t>::stream(s, indent + "  ", v.X);
    s << indent << "Z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOVER_G2_MESSAGE_MOVIMENTO_H
